name: ${{values.app_name}}-cicd
on: 
  push:
    branches:
      - main
    paths:
      - src/**

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: docker login
      uses: docker/login-action@v3
      with:
        username: ${{ '${{ secrets.DOCKERHUB_USERNAME }}' }}
        password: ${{ '${{ secrets.DOCKERHUB_TOKEN }}' }}
    
    - name: Get short commit id
      shell: bash
      run: |
        echo "COMMIT_ID=${GITHUB_SHA::6}" >> ${GITHUB_ENV}

    - name: Build and Push docker image
      uses: docker/build-push-action@v6
      with: 
        push: true
        tags: aumthakkar/${{values.app_name}}:${{ '${{ env.COMMIT_ID}}' }}
    
    outputs:
      commit_id: ${{ '${{ env.COMMIT_ID}}' }}

  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      - name: Checkout github repo
        uses: actions/checkout@v6

      - name: Update tag in values.yaml
        run: |
          sudo apt update && sudo apt install python3-pip -y
          pip install yq --break-system-packages
          echo ${{ '${{ needs.ci.outputs.commit_id }}' }}
          yq -Yi '.image.tag = "${{ '${{ needs.ci.outputs.commit_id }}' }}"' charts/${{ values.app_name }}/values-${{ values.app_env }}.yaml

      - name: Commit your changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "push the image with tag - ${{ '${{ needs.ci.outputs.commit_id }}' }}"

      - name: Install ArgoCD CLI
        shell: bash
        run: |
          curl -ksSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/download/v3.2.2/argocd-linux-amd64
          sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
          sudo chmod +x /usr/local/bin/argocd
        
      - name: Sync App using ArgoCD
        shell: bash
        run: |
          argocd login argocd-server.argocd \
            --grpc-web \
            --insecure \
            --username ${{ '${{ secrets.ARGOCD_USERNAME }}' }} \
            --password ${{ '${{ secrets.ARGOCD_PASSWORD }}' }}

      - name: ArgoCD App Create and Sync
        shell: bash
        run: |
          repo="https://github.com/aum-thakkar/${{values.app_name}}.git"

          argocd repo list | grep ${repo} || argocd repo add ${repo}
          
          argocd app get ${{values.app_name}} || argocd app create ${{values.app_name}} \
          --dest-namespace ${{values.app_env}} \
          --dest-server https://kubernetes.default.svc \
          --path charts/${{values.app_name}} \
          --repo ${repo} \
          --revision main \
          --sync-policy manual \
          --sync-option CreateNamespace=true \
          --values values-${{values.app_env}}.yaml

          # Sync the App
          argocd app sync ${{values.app_name}}
          argocd app wait ${{values.app_name}} --timeout 120


          
